name: pantry_pal
description: "PantryPal - Your friendly kitchen companion"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.3.0

  # UI/Fonts
  google_fonts: ^6.2.1

  # Utilities
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.3
  appinio_swiper: ^2.1.1
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.0
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
